remote_theme: just-the-docs/just-the-docs

title: Enterprise Internals

description: >-
  How Enterprise Cloud, AI, Architecture, Governance, 
  Automation, and Technology Decision-Making actually work in practice

url: "https://gitbajajrahul001.github.io"
baseurl: "/enterprise-internals"

search_enabled: true

heading_anchors: true

permalink: pretty

footer_content: " "

plugins:
  - jekyll-remote-theme