theme: minima

title: Enterprise Mechanics

description: >-
  How Enterprise Cloud, AI, Architecture, Governance,
  Automation, and Technology Decision-Making actually work in practice

url: "https://gitbajajrahul001.github.io"
baseurl: "/enterprise-mechanics"

sass:
  style: compressed

header_pages:
  - index.md
  - about.md

markdown: kramdown

plugins:
  - jekyll-feed

permalink: pretty